baseurl: ''
permalink: pretty
title: 'Syry'

logo:
  mobile: "images/logo/logo.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  desktop_width: "120px"

collections:
  services:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
